name: Buy lotto

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * 1  # Every Monday at 06:00 PM (KST)

jobs:
  buy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python scripts
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COUNT: ${{ secrets.COUNT }}
          BUY_WEBHOOK_URL:  ${{ secrets.BUY_WEBHOOK_URL }}
        run: |
          make buy

      - uses: gautamkrishnar/keepalive-workflow@v2
